-- SFQuest_Tweaks.lua
-- Aggiunge tag vanilla agli item per il sistema di quest
--
-- NOTA: Questi sono tag vanilla (HasMetal, CannedFood, Fish, etc.)
-- che esistono già nel gioco. Non serve registrarli. FORSE IN B42 Non esistono più però

local manager = ScriptManager.instance

-- Helper function: aggiunge un tag ad un item preservando i tag esistenti
-- Usa l'API Java diretta: getTags():add(ItemTag)
local function addTag(itemName, tagName)
    local item = manager:getItem(itemName)
    if item then
        item:getTags():add(ItemTag.get(ResourceLocation.of(tagName)))
    else
        print("[SFQuest] addTag: Item non trovato - " .. itemName)
    end
end

function SFQuest_Tweaks()
    -- CannedFood con HasMetal
    addTag("Base.CannedCorn", "HasMetal")
    addTag("Base.CannedCorn", "CannedFood")
    addTag("Base.CannedMushroomSoup", "HasMetal")
    addTag("Base.CannedMushroomSoup", "CannedFood")
    addTag("Base.CannedPeas", "HasMetal")
    addTag("Base.CannedPeas", "CannedFood")
    addTag("Base.CannedPotato2", "HasMetal")
    addTag("Base.CannedPotato2", "CannedFood")
    addTag("Base.CannedSardines", "HasMetal")
    addTag("Base.CannedSardines", "CannedFood")
    addTag("Base.CannedTomato2", "HasMetal")
    addTag("Base.CannedTomato2", "CannedFood")
    addTag("Base.CannedCarrots2", "HasMetal")
    addTag("Base.CannedCarrots2", "CannedFood")
    addTag("Base.CannedChili", "HasMetal")
    addTag("Base.CannedChili", "CannedFood")
    addTag("Base.CannedBolognese", "HasMetal")
    addTag("Base.CannedBolognese", "CannedFood")
    addTag("Base.CannedCornedBeef", "HasMetal")
    addTag("Base.CannedCornedBeef", "CannedFood")
    addTag("Base.TinnedSoup", "HasMetal")
    addTag("Base.TinnedSoup", "CannedFood")
    addTag("Base.TinnedBeans", "HasMetal")
    addTag("Base.TinnedBeans", "CannedFood")
    addTag("Base.TunaTin", "HasMetal")
    addTag("Base.TunaTin", "CannedFood")
    addTag("Base.CannedFruitCocktail", "HasMetal")
    addTag("Base.CannedFruitCocktail", "CannedFood")
    addTag("Base.CannedFruitBeverage", "HasMetal")
    addTag("Base.CannedFruitBeverage", "CannedFood")
    addTag("Base.CannedPeaches", "HasMetal")
    addTag("Base.CannedPeaches", "CannedFood")
    addTag("Base.CannedPineapple", "HasMetal")
    addTag("Base.CannedPineapple", "CannedFood")
    addTag("Base.CannedMilk", "HasMetal")
    addTag("Base.CannedMilk", "CannedFood")

    -- AmmoBox
    addTag("Base.Bullets9mmBox", "AmmoBox")
    addTag("Base.Bullets45Box", "AmmoBox")
    addTag("Base.Bullets44Box", "AmmoBox")
    addTag("Base.Bullets38Box", "AmmoBox")
    addTag("Base.ShotgunShellsBox", "AmmoBox")
    addTag("Base.223Box", "AmmoBox")
    addTag("Base.308Box", "AmmoBox")
    addTag("Base.556Box", "AmmoBox")

    -- DeadAnimal
    addTag("Base.DeadBird", "DeadAnimal")
    addTag("Base.DeadRabbit", "DeadAnimal")
    addTag("Base.DeadSquirrel", "DeadAnimal")

    -- Fish
    addTag("Base.Bass", "Fish")
    addTag("Base.Catfish", "Fish")
    addTag("Base.Crappie", "Fish")
    addTag("Base.Panfish", "Fish")
    addTag("Base.Perch", "Fish")
    addTag("Base.Pike", "Fish")
    addTag("Base.Trout", "Fish")

    -- ForagedPlant
    addTag("Base.Basil", "ForagedPlant")
    addTag("Base.Chives", "ForagedPlant")
    addTag("Base.Cilantro", "ForagedPlant")
    addTag("Base.Oregano", "ForagedPlant")
    addTag("Base.Parsley", "ForagedPlant")
    addTag("Base.Rosemary", "ForagedPlant")
    addTag("Base.Sage", "ForagedPlant")
    addTag("Base.Thyme", "ForagedPlant")

    -- Medicine
    addTag("Base.Pills", "Medicine")
    addTag("Base.PillsAntiDep", "Medicine")
    addTag("Base.PillsBeta", "Medicine")
    addTag("Base.PillsSleepingTablets", "Medicine")
    addTag("Base.PillsVitamins", "Medicine")

    -- Pistol
    addTag("Base.Pistol", "Pistol")
    addTag("Base.Pistol2", "Pistol")
    addTag("Base.Pistol3", "Pistol")
    addTag("Base.Revolver", "Pistol")
    addTag("Base.Revolver_Long", "Pistol")
    addTag("Base.Revolver_Short", "Pistol")

    -- Rifle
    addTag("Base.AssaultRifle", "Rifle")
    addTag("Base.AssaultRifle2", "Rifle")
    addTag("Base.HuntingRifle", "Rifle")
    addTag("Base.VarmintRifle", "Rifle")

    -- Shotgun
    addTag("Base.DoubleBarrelShotgun", "Shotgun")
    addTag("Base.DoubleBarrelShotgunSawnoff", "Shotgun")
    addTag("Base.Shotgun", "Shotgun")
    addTag("Base.ShotgunSawnoff", "Shotgun")

    -- SkillBook
    addTag("Base.BookCarpentry1", "SkillBook")
    addTag("Base.BookCarpentry2", "SkillBook")
    addTag("Base.BookCarpentry3", "SkillBook")
    addTag("Base.BookCarpentry4", "SkillBook")
    addTag("Base.BookCarpentry5", "SkillBook")
    addTag("Base.BookCooking1", "SkillBook")
    addTag("Base.BookCooking2", "SkillBook")
    addTag("Base.BookCooking3", "SkillBook")
    addTag("Base.BookCooking4", "SkillBook")
    addTag("Base.BookCooking5", "SkillBook")
    addTag("Base.BookElectrician1", "SkillBook")
    addTag("Base.BookElectrician2", "SkillBook")
    addTag("Base.BookElectrician3", "SkillBook")
    addTag("Base.BookElectrician4", "SkillBook")
    addTag("Base.BookElectrician5", "SkillBook")
    addTag("Base.BookFarming1", "SkillBook")
    addTag("Base.BookFarming2", "SkillBook")
    addTag("Base.BookFarming3", "SkillBook")
    addTag("Base.BookFarming4", "SkillBook")
    addTag("Base.BookFarming5", "SkillBook")
    addTag("Base.BookFirstAid1", "SkillBook")
    addTag("Base.BookFirstAid2", "SkillBook")
    addTag("Base.BookFirstAid3", "SkillBook")
    addTag("Base.BookFirstAid4", "SkillBook")
    addTag("Base.BookFirstAid5", "SkillBook")
    addTag("Base.BookFishing1", "SkillBook")
    addTag("Base.BookFishing2", "SkillBook")
    addTag("Base.BookFishing3", "SkillBook")
    addTag("Base.BookFishing4", "SkillBook")
    addTag("Base.BookFishing5", "SkillBook")
    addTag("Base.BookForaging1", "SkillBook")
    addTag("Base.BookForaging2", "SkillBook")
    addTag("Base.BookForaging3", "SkillBook")
    addTag("Base.BookForaging4", "SkillBook")
    addTag("Base.BookForaging5", "SkillBook")
    addTag("Base.BookMechanic1", "SkillBook")
    addTag("Base.BookMechanic2", "SkillBook")
    addTag("Base.BookMechanic3", "SkillBook")
    addTag("Base.BookMechanic4", "SkillBook")
    addTag("Base.BookMechanic5", "SkillBook")
    addTag("Base.BookMetalWelding1", "SkillBook")
    addTag("Base.BookMetalWelding2", "SkillBook")
    addTag("Base.BookMetalWelding3", "SkillBook")
    addTag("Base.BookMetalWelding4", "SkillBook")
    addTag("Base.BookMetalWelding5", "SkillBook")
    addTag("Base.BookTailoring1", "SkillBook")
    addTag("Base.BookTailoring2", "SkillBook")
    addTag("Base.BookTailoring3", "SkillBook")
    addTag("Base.BookTailoring4", "SkillBook")
    addTag("Base.BookTailoring5", "SkillBook")
    addTag("Base.BookTrapping1", "SkillBook")
    addTag("Base.BookTrapping2", "SkillBook")
    addTag("Base.BookTrapping3", "SkillBook")
    addTag("Base.BookTrapping4", "SkillBook")
    addTag("Base.BookTrapping5", "SkillBook")

    print("[SFQuest] Tweaks applicati con successo")
end

-- Events.OnGameBoot.Add(SFQuest_Tweaks)
